import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-screen-xl px-4 py-2">{children}</body>
    </html>
  );
}
